spring:
  datasource:
    username:
    password:
    url: jdbc:h2:mem:project
  h2:
    console:
      enabled: true
      path: /h2-console/
      settings:
        web-allow-others: true
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG